name: Attendify Planning CI Docker Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t attendify-planning planning/

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name attendify-planning-container attendify-planning
          sleep 5

      - name: Test API endpoint
        run: |
          curl --request POST \
            --header "Content-Type: application/json" \
            --data '{"summary":"Test Event","start":"2025-03-22T09:00:00","end":"2025-03-22T10:00:00"}' \
            http://localhost:5000/create-event || exit 1

      - name: Stop Docker container
        run: docker stop attendify-planning-container
